version: "3.9"

services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    ports:
      - "8000:8000"
    links: 
      - db
    volumes: 
      - .:/app
    depends_on:
      - 'db'
    networks:
      - dev-network
  db:
    image: 'mariadb:latest'
    restart: 'always'
    container_name: db
    ports:
      - "3306:3306"
    volumes: 
      - ./data/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - dev-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
    networks:
      - dev-network
    depends_on:
      - 'db'
networks:
  dev-network:
    driver: bridge